### ISSUE TITLE
Support Circom 2.0

### ISSUE THREAD

**Issue by oskarth** [gakonst/ark-circom#8]
# Problem

I want to be able to use circuits written and compiled with the new Rust based Circom 2.0 compiler https://github.com/iden3/circom as opposed to the current JS based one https://github.com/iden3/circom_old

When I try to use `wasm` and `r1cs` files generated by Circom 2.0 as per example usage (https://github.com/gakonst/ark-circom#example) it fails to compile.

I might be missing something fundamental here, but based on the release date of Circom 2.0 and the last update of this library it doesn't seem like Circom 2.0 support currently exists.

# Details

Note: I'm not really a Rust programmer, nor am I that familiar with WebAssembly or the Circom compiler, so these are just some rough notes based on me trying to solve the above problem.

It seems to me things have changed w.r.t. the WASM interface. The first error we see is about a missing function:

```
thread 'main' panicked at 'function getFrLen not found', /home/oskarth/.cargo/git/checkouts/ark-circom-e5b2a9b30398f2b3/729ea33/src/witness/circom.rs:80:33
```

We can see this being added here: https://github.com/gakonst/ark-circom/blob/master/src/witness/circom.rs#L19

Old Circom 1.0 JS compiler has it here: https://github.com/iden3/circom_old/blob/c311ae355239bae76a83b92070cb21d249e77465/ports/wasm/build_runtime.js#L926

However, this doesn't exist in the new Circom 2.0 compiler.

Here's where the new WASM interface seems to be defined: https://github.com/iden3/circom/blob/f673727a97f972dad27df7cc5e4c38e45b37966d/code_producers/src/wasm_elements/witness_calculator.js#L10

There might also be other differences.

## Attempt

I started trying to make compiler errors go away by adding stubs etc in a naive fashion. This resolved a few compiler errors.

See here for WIP debug branch diff: https://github.com/gakonst/ark-circom/compare/master...oskarth:master

I added a Circom 2 feature flag to switch between the two. This can probably be done cleaner with separate WitnessCalculator implementations etc, but conceptually it should work for not breaking existing compatibility.

I'm testing it from https://github.com/oskarth/hello-ark-circom and can confirm it works fine with Circom 1.0 compiled wasm/r1cs files.

After the initial compiler errors, I ran into things like not finding the prime 21888242871839275222246405745257275088548364400416034343698204186575808495617 in the WASM memory (?). I hardcoded some values based on circom-1 output just to see where things would end up.

The last compiler error I got was "thread 'main' panicked at 'Error: This parser only supports 32-byte fields" which happens here: https://github.com/gakonst/ark-circom/compare/master...oskarth:master#diff-97b759aa5cd8e3f3769343c3b3b2ae638f500527f0bd6e026c1a929273c851ebR96

For some reason it is 1 and not 32. That's where I stopped debugging.

## Going forward

It isn't obvious to me how hard it is to implement Circom 2.0 support for ark-circom here, or if this is something that is planned. If it is just a few tweaks to get it to work, I can keep working on it with some pointers. If it requires more work, well, here's a feature request :)

# Acceptance criteria

Circuits compiled with Rust-based Circom 2.0 compiler are able to generate witness, prove and verify.

---

^ @gakonst @kobigurk

**Comment by gakonst** [comment]
Thanks for digging in. I have not looked at Circom 2.0 yet, but the iden3 team shared [this](https://docs.google.com/document/d/1P0j9zXjJRkhnyPT03VjxYBUySC8l4k41ZQ5LY7uyQnw/edit?usp=sharing) doc explaining the WASM Interface. Does that help perhaps?

**Comment by oskarth** [comment]
Thanks! Took another stab at this and made it self-contained with a test. See https://github.com/gakonst/ark-circom/pull/10 for current WIP

**Comment by philsippl** [comment]
@oskarth Implemented a few more functions from the spec in #14 and your testcase works now: `cargo test --features circom-2 groth16_proof_circom2`

**Comment by oskarth** [comment]
Brief update: seems to works well enough to verify non trivial proofs such as Tornado Cash and RLN - https://github.com/vacp2p/zerokit/tree/master/rln

A bit more real-world usage/testing and we should be able to turn on this flag by default.

**Comment by philsippl** [comment]
@oskarth That's awesome! 
I've originally started working on ark-circom for another use-case, but we now also ported the semaphore part of [zk-kit](https://github.com/appliedzkp/zk-kit) to Rust and use ark-circom with circom 2 there. Might be interesting for you guys as well: https://github.com/worldcoin/semaphore-rs

**Comment by gakonst** [comment]
Very nice! Given the above, closing this issue, and we can track new things separately. Thanks all!

**Comment by oskarth** [comment]
@philsippl ah nice, definitely similar to our use case :) thanks for sharing!
